version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: doc24x7-postgres
    restart: always
    environment:
      POSTGRES_USER: docuser
      POSTGRES_PASSWORD: docpass
      POSTGRES_DB: doc24x7
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
